const express = require('express');

const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const complaintRoutes = require('./complaintRoutes');
const departmentRoutes = require('./departmentRoutes');
const feedbackRoutes = require('./feedbackRoutes');
const aiRoutes = require('./aiRoutes');
const announcementRoutes = require('./announcementRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const geoRoutes = require('./geoRoutes');
const adminRoutes = require('./adminRoutes');
const updateRoutes = require('./updateRoutes');
const governanceRoutes = require('./governanceRoutes');
const aiAssistantRoutes = require('./aiAssistantRoutes');
const analyticsRoutes = require('./analyticsRoutes');
const intelligenceRoutes = require('./intelligenceRoutes');
const transparencyRoutes = require('./transparencyRoutes');
const eventMonitorRoutes = require('./eventMonitorRoutes');
const infrastructureRoutes = require('./infrastructureRoutes');
const voiceRoutes = require('./voiceRoutes');
const notificationRoutes = require('./notificationRoutes');
const updateSourceRoutes = require('./updateSourceRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/complaints', complaintRoutes);
router.use('/departments', departmentRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/feedbacks', feedbackRoutes);
router.use('/ai', aiRoutes);
router.use('/announcements', announcementRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/geo', geoRoutes);
router.use('/admin', adminRoutes);
router.use('/updates', updateRoutes);
router.use('/governance', governanceRoutes);
router.use('/ai-assistant', aiAssistantRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/intelligence', intelligenceRoutes);
router.use('/transparency', transparencyRoutes);
router.use('/events/monitor', eventMonitorRoutes);
router.use('/infrastructure', infrastructureRoutes);
router.use('/voice', voiceRoutes);
router.use('/notifications', notificationRoutes);
router.use('/update-sources', updateSourceRoutes);

module.exports = router;
